import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { ApolloClient, InMemoryCache, DefaultOptions } from '@apollo/client';
import Image from 'next/image';
import HeaderImage from '../public/img/header-default-image.png';
import DOMPurify from 'isomorphic-dompurify';
import { GET_PAGE } from '../queries/get_page';

const defaultOptions: DefaultOptions = {
	watchQuery: {
		fetchPolicy: 'no-cache',
		errorPolicy: 'ignore',
	},
	query: {
		fetchPolicy: 'no-cache',
		errorPolicy: 'all',
	},
};

const client = new ApolloClient({
	uri: 'https://www.idinheiro.com.br/graphql',
	cache: new InMemoryCache(),
	connectToDevTools: true,
	defaultOptions,
});

export const getStaticProps: GetStaticProps = async () => {
	const { data } = await client.query({
		query: GET_PAGE,
		variables: { uri: '/contato' },
	});

	return {
		props: {
			data: data.page,
		},
	};
};

interface IHomeProps {
	data: any;
}

const Home: NextPage<IHomeProps> = props => {
	const { data } = props;

	return (
		<div className=''>
			<Head>
				<title>Tailwind</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div>
					{data.title && data.bannerPaginasInternas?.subtitulo && (
						<div className='bg-gradient-to-b from-black to-neutral-700 w-full flex flex-col items-center py-12'>
							<Image src={HeaderImage} alt='Header' />
							<h1 className='uppercase  pb-8 pt-12 text-white text-3xl font-bold'>
								{data.title}
							</h1>
							<h2 className='text-white pb-8'>
								{data.bannerPaginasInternas?.subtitulo}
							</h2>
						</div>
					)}

					<div
						className='[&_a]:text-blue-400 [&_a]:underline container mx-auto px-2 pt-6'
						dangerouslySetInnerHTML={{
							__html: DOMPurify.sanitize(data.content),
						}}
					/>
				</div>
			</main>
		</div>
	);
};

export default Home;
